
import { useMemo } from 'react';
import type { Player, User, MarketDataPoint } from '../types';

export const useMockData = () => {
  const players: Player[] = useMemo(() => [
    {
      id: 1,
      name: 'Jude Bellingham',
      age: 20,
      position: 'Midfielder',
      club: 'Real Madrid',
      nationality: 'England',
      imageUrl: 'https://picsum.photos/seed/jude/400/400',
      currentValue: 180000000,
      predictedValue: 250000000,
      potential: 'Elite',
      injuryRisk: 10,
      stats: { appearances: 35, goals: 19, assists: 6 },
    },
    {
      id: 2,
      name: 'Lamine Yamal',
      age: 16,
      position: 'Winger',
      club: 'FC Barcelona',
      nationality: 'Spain',
      imageUrl: 'https://picsum.photos/seed/lamine/400/400',
      currentValue: 75000000,
      predictedValue: 180000000,
      potential: 'Elite',
      injuryRisk: 25,
      stats: { appearances: 40, goals: 7, assists: 10 },
    },
    {
      id: 3,
      name: 'Florian Wirtz',
      age: 21,
      position: 'Attacking Midfielder',
      club: 'Bayer Leverkusen',
      nationality: 'Germany',
      imageUrl: 'https://picsum.photos/seed/wirtz/400/400',
      currentValue: 110000000,
      predictedValue: 160000000,
      potential: 'Elite',
      injuryRisk: 15,
      stats: { appearances: 38, goals: 11, assists: 11 },
    },
    {
      id: 4,
      name: 'Warren Zaïre-Emery',
      age: 18,
      position: 'Midfielder',
      club: 'Paris Saint-Germain',
      nationality: 'France',
      imageUrl: 'https://picsum.photos/seed/zaire/400/400',
      currentValue: 60000000,
      predictedValue: 120000000,
      potential: 'Elite',
      injuryRisk: 5,
      stats: { appearances: 32, goals: 2, assists: 5 },
    },
    {
        id: 5,
        name: 'Arda Güler',
        age: 19,
        position: 'Attacking Midfielder',
        club: 'Real Madrid',
        nationality: 'Turkey',
        imageUrl: 'https://picsum.photos/seed/arda/400/400',
        currentValue: 30000000,
        predictedValue: 90000000,
        potential: 'Starter',
        injuryRisk: 30,
        stats: { appearances: 10, goals: 6, assists: 0 },
      },
      {
        id: 6,
        name: 'Evan Ferguson',
        age: 19,
        position: 'Striker',
        club: 'Brighton',
        nationality: 'Ireland',
        imageUrl: 'https://picsum.photos/seed/ferguson/400/400',
        currentValue: 60000000,
        predictedValue: 100000000,
        potential: 'Starter',
        injuryRisk: 12,
        stats: { appearances: 27, goals: 6, assists: 0 },
      },
      {
        id: 7,
        name: 'Benjamin Sesko',
        age: 21,
        position: 'Striker',
        club: 'RB Leipzig',
        nationality: 'Slovenia',
        imageUrl: 'https://picsum.photos/seed/sesko/400/400',
        currentValue: 50000000,
        predictedValue: 95000000,
        potential: 'Starter',
        injuryRisk: 8,
        stats: { appearances: 31, goals: 14, assists: 2 },
      },
      {
        id: 8,
        name: 'Rico Lewis',
        age: 19,
        position: 'Full-back',
        club: 'Manchester City',
        nationality: 'England',
        imageUrl: 'https://picsum.photos/seed/lewis/400/400',
        currentValue: 38000000,
        predictedValue: 70000000,
        potential: 'Bench',
        injuryRisk: 18,
        stats: { appearances: 16, goals: 2, assists: 0 },
      },
  ], []);

  const leaderboard: User[] = useMemo(() => [
    { id: 1, name: 'Alex Johnson', portfolioValue: 152340000, rank: 1 },
    { id: 2, name: 'Ben Carter', portfolioValue: 141890000, rank: 2 },
    { id: 3, name: 'Chloe Davis', portfolioValue: 129500000, rank: 3 },
    { id: 4, name: 'David Evans', portfolioValue: 115200000, rank: 4 },
  ], []);

  const marketData: MarketDataPoint[] = useMemo(() => [
    { date: 'Jan', value: 100 },
    { date: 'Feb', value: 105 },
    { date: 'Mar', value: 110 },
    { date: 'Apr', value: 108 },
    { date: 'May', value: 115 },
    { date: 'Jun', value: 122 },
  ], []);

  return { players, leaderboard, marketData };
};
